name: CI

on: [push]

jobs:
  vscode-extension:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - name: Test Linux
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
      timeout-minutes: 2
    - name: Test Mac/Windows
      run: npm test
      if: runner.os != 'Linux'
